Nc news 7
cCody34/nc-news pull request #7
Opened 2023-08-15 14:50 UTC by cCody34

2023-08-15 15:18 UTC, Slyose reviewed
Very close! A few comments to consider then please resubmit a PR!

2023-08-15 15:18 UTC, Slyose commented on db/models/comments-models.js
> +  }
This doesn't have to be a custom error - psql will throw an error if you give the wrong data type to the insert query. Where you can, it's better to take advantage of this rather than writing your own logic for it

2023-08-15 15:18 UTC, Slyose commented on __tests__/app.test.js
> +        });
Great tests so far. Would also be good to see a test for a status 201, where your endpoint ignores unnecessary properties

2023-08-16 08:00 UTC, Augs0 requested changes
Hey Charlotte, nice work implementing Modou's feedback 💪  I've left a few comments where you have unnecessary details. Please remove those then you are free to merge ❇️

2023-08-16 08:00 UTC, Augs0 commented on db/error-handlers/error.js
> +    err.constraint === "comments_author_fkey" ||
These constraint parts are not needed. The codes are specific to each issue so are enough to find the error we are looking for

2023-08-16 08:00 UTC, Augs0 commented on db/error-handlers/error.js
> +  if (err.constraint === "comments_article_id_fkey") {
Same here, better to use the codes

2023-08-16 10:04 UTC, merged